"""zones + assignment + status string

Revision ID: 128cb4319dd2
Revises: 840a0db5a34d
Create Date: 2026-01-30 11:13:42.358770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '128cb4319dd2'
down_revision = '840a0db5a34d'
branch_labels = None
depends_on = None


def upgrade():
    # 1) requests.status: enum -> varchar
    op.execute("ALTER TABLE requests ALTER COLUMN status TYPE VARCHAR(30) USING status::text;")

    # 2) zones table
    op.create_table(
        "zones",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("venue_id", sa.Integer(), sa.ForeignKey("venues.id"), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("default_exit_id", sa.Integer(), sa.ForeignKey("exits.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )

    # 3) requests: assignment + zone_id
    op.add_column("requests", sa.Column("assigned_to", sa.String(length=80), nullable=True))
    op.add_column("requests", sa.Column("assigned_at", sa.DateTime(), nullable=True))
    op.add_column("requests", sa.Column("zone_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_requests_zone_id_zones", "requests", "zones", ["zone_id"], ["id"])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('REQUESTED', 'RETRIEVING', 'READY', 'PICKED_UP', name='requeststatus'),
               existing_nullable=False)
        batch_op.drop_column('zone_id')
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('assigned_to')

    op.drop_table('zones')
    # ### end Alembic commands ###
