"""add scheduled_for to requests

Revision ID: 1b8aa32f17bc
Revises: 2b25c31c8d10
Create Date: 2026-01-30 13:41:21.231592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8aa32f17bc'
down_revision = '2b25c31c8d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_for', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('scheduled_for')

    # ### end Alembic commands ###
